<?php

/**
 * Copyright 2021, 2024 5 Mode
 *
 * This file is part of SnipSwap.
 *
 * SnipSwap is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * SnipSwap is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.  
 * 
 * You should have received a copy of the GNU General Public License
 * along with SnipSwap. If not, see <https://www.gnu.org/licenses/>.
 *
 * const.php.inc
 * 
 * Additional PHP constants.
 *
 * @author Daniele Bonini <my25mb@aol.com>
 * @copyrights (c) 2016, 2024, 5 Mode
  */

if (!defined("PHP_BR")) {
  define('PHP_BR', "<br>");
}
if (!defined("PHP_CN")) {
  define('PHP_CN', "zh-CN");
}
if (!defined("PHP_EN")) {
  define('PHP_EN', "en-US");
}
if (!defined("PHP_ES")) {
  define('PHP_ES', "es-ES");
}
if (!defined("PHP_FR")) {
  define('PHP_FR', "fr-FR");
}
if (!defined("PHP_HYPHEN")) {
  define('PHP_HYPHEN', "-");
}
if (!defined("PHP_IT")) {
  define('PHP_IT', "it-IT");
}
if (!defined("PHP_PIPE")) {
  define('PHP_PIPE', "|");
}
if (!defined("PHP_SLASH")) {
  define('PHP_SLASH', "/");
}
if (!defined("PHP_SPACE")) {
  define('PHP_SPACE', " ");
}
if (!defined("PHP_STR")) {
  define('PHP_STR', "");
}
if (!defined("PHP_TILDE")) {
  define('PHP_TILDE', "~");
}
if (!defined("PHP_UNDERSCORE")) {
  define('PHP_UNDERSCORE', "_");
}